dataset_name: assist2009
raw_path: data/assist2009/skill_builder_data_corrected_collapsed.csv
dpath: data/assist2009
configf: configs/data_config.json


min_seq_len: 3
maxlen: 200
kfold: 5
folds: [0,1,2,3,4]
emb_path: ""

train_valid_original_file: train_valid.csv
train_valid_file: train_valid_sequences.csv
test_original_file: test.csv
test_file: test_sequences.csv
test_window_file: test_window_sequences.csv

gen_question_level: true
test_question_file: test_question_sequences.csv
test_question_window_file: test_question_window_sequences.csv
train_valid_original_file_quelevel: train_valid_quelevel.csv
train_valid_file_quelevel: train_valid_sequences_quelevel.csv
test_file_quelevel: test_sequences_quelevel.csv
test_window_file_quelevel: test_window_sequences_quelevel.csv
test_original_file_quelevel: test_quelevel.csv



